version: '3'

services:
  ideas_portal_dev:
    container_name: ideas_portal_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d
    volumes:
      - .:/extension
    env_file:
      - .ideas_portal_dev.env

  ideas_portal_bash:
    container_name: ideas_portal_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .ideas_portal_dev.env

  ideas_portal_test:
    container_name: ideas_portal_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
    env_file:
      - .ideas_portal_dev.env
